# Generated by Django 5.1.1 on 2024-09-08 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=8, verbose_name='Название группы')),
                ('group_course', models.IntegerField(default=1, verbose_name='Номер курса')),
            ],
            options={
                'verbose_name': 'Учебная группа',
                'verbose_name_plural': 'Учебные группы',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=250, verbose_name='ФИО Преподавателя')),
                ('teacher_is_active', models.BooleanField(default=True, verbose_name='Действующий сотрудник')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=120, verbose_name='Название дисциплины')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetable.teacher')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_number', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], max_length=1, verbose_name='Номер пары')),
                ('cabinet_number', models.CharField(max_length=6, verbose_name='Номер кабинета')),
                ('pair_begin_time', models.TimeField(verbose_name='Время начала пары')),
                ('pair_end_time', models.TimeField(verbose_name='Время конца пары')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.group', verbose_name='Учебная группа')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetable.subject', verbose_name='Учебная дисциплина')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetable.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
            },
        ),
    ]
