# Generated by Django 5.1.1 on 2024-09-08 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_timetable_pair_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetable.teacher', verbose_name='Преподаватель'),
        ),
    ]
