# Generated by Django 5.1.1 on 2024-09-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_timetable_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='distant_pair',
            field=models.BooleanField(default=False, verbose_name='Дистанционное занятие'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='cabinet_number',
            field=models.CharField(blank=True, max_length=6, verbose_name='Номер кабинета'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day_of_week',
            field=models.CharField(choices=[('0', 'Понедельник'), ('1', 'Вторник'), ('2', 'Среда'), ('3', 'Четверг'), ('4', 'Пятница'), ('5', 'Суббота')], default='0', max_length=1, verbose_name='День недели'),
        ),
    ]
