# Generated by Django 5.1.1 on 2024-09-08 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_timetable_distant_pair_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['pair_number', 'day_of_week'], 'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_substitution', models.DateField(verbose_name='Дата замещения')),
                ('cabinet_on_substitution', models.CharField(blank=True, max_length=6, verbose_name='Кабинет')),
                ('distant_pair', models.BooleanField(default=False, verbose_name='Дистанционное занятие')),
                ('original_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timetable', verbose_name='Пара для замены')),
                ('subject_on_substitution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.subject', verbose_name='Предмет для замещения')),
                ('teacher_on_substitution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.teacher', verbose_name='Преподаватель на замещаемой паре')),
            ],
            options={
                'verbose_name': 'Замещение',
                'verbose_name_plural': 'Замещения',
                'ordering': ['-date_of_substitution'],
            },
        ),
    ]
