# Generated by Django 5.1.1 on 2024-09-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_alter_timetable_options_substitution'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='denominator_options',
            field=models.CharField(choices=[('n', 'Числитель'), ('d', 'Знаменатель'), ('b', 'Оба')], default='b', max_length=1, verbose_name='Настройка числителя/знаменателя'),
        ),
    ]
