# Generated by Django 5.1.1 on 2024-09-21 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_timetable_denominator_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='substitution',
            name='group_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetable.group'),
            preserve_default=False,
        ),
    ]
