# Generated by Django 5.1.1 on 2024-09-22 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_substitution_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substitution',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.group', verbose_name='Учебная группа'),
        ),
    ]
