# Generated by Django 5.1.1 on 2024-12-25 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_alter_substitution_group_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['day_of_week', 'pair_number'], 'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_exam', models.TimeField(verbose_name='Время экзамена')),
                ('date_of_exam', models.DateField(verbose_name='Дата экзамена')),
                ('is_consultation', models.BooleanField(default=False, verbose_name='Консультация')),
                ('cabinet_for_exam', models.CharField(blank=True, max_length=6, verbose_name='Номер кабинета')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.group', verbose_name='Учебная группа')),
                ('subject_for_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Экзамен',
                'verbose_name_plural': 'Экзамены',
            },
        ),
    ]
