# Generated by Django 5.1.1 on 2024-12-25 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_alter_timetable_options_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.exam', verbose_name='Выбранный экзамен')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.teacher', verbose_name='Экзаменатор')),
            ],
            options={
                'verbose_name': 'Экзаменатор',
                'verbose_name_plural': 'Экзаменаторы',
            },
        ),
    ]
