# Generated by Django 5.1.1 on 2024-09-08 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_ordering', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificatetype',
            options={'verbose_name': 'Вид справки', 'verbose_name_plural': 'Виды справок'},
        ),
    ]
