# Generated by Django 5.1.1 on 2024-09-21 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_ordering', '0002_alter_certificatetype_options'),
        ('student_list', '0002_alter_student_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificaterequest',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='certificaterequest',
            name='student_fio',
        ),
        migrations.RemoveField(
            model_name='certificaterequest',
            name='student_group',
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='student_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_list.student', verbose_name='Студент'),
            preserve_default=False,
        ),
    ]
