# Generated by Django 5.1.1 on 2024-09-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_ordering', '0003_remove_certificaterequest_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterequest',
            name='organization_full_name',
            field=models.TextField(blank=True, null=True, verbose_name='Полное название организации'),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='voenkomat_full_name',
            field=models.TextField(blank=True, null=True, verbose_name='Полное название военкомата'),
        ),
    ]
