# Generated by Django 5.1.1 on 2024-09-21 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetable', '0007_timetable_denominator_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.TextField(verbose_name='ФИО Студента')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.group')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
    ]
