# Generated by Django 5.1.1 on 2024-09-21 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_list', '0001_initial'),
        ('timetable', '0007_timetable_denominator_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.group', verbose_name='Учебная группа'),
        ),
    ]
