# Generated by Django 5.1.1 on 2024-09-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_list', '0002_alter_student_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='telegram_nickname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Никнейм в Telegram'),
        ),
        migrations.AddField(
            model_name='student',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
