# Generated by Django 5.1.1 on 2024-09-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_list', '0003_student_telegram_nickname_student_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Подтвержденный профиль'),
        ),
    ]
